# Generated by Django 4.2.7 on 2023-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_ver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_verification',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код верификации'),
        ),
    ]
