# Generated by Django 4.2.7 on 2023-11-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='version',
            table='catalog_version',
        ),
    ]
