# Generated by Django 4.2.7 on 2023-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_options_alter_version_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
